### ISSUE TITLE
Plattformunabhängigkeit von fopen() und fwrite()

### ISSUE THREAD

**Issue by braeuert** [EndoplasmaticReticulum/bitmap#1]
Hallo,

beim Programmieren mit der Bibliothek ist mir unter Windows immer wieder ein Fehler beim Einlesen der Bitmap-Dateien untergekommen. Unter Linux funktionierte beim Testprogramm bislang problemfrei. 
Gemäß [http://stackoverflow.com/questions/3187693/fread-ftell-apparently-broken-under-windows-works-fine-under-linux](url) funktioniert das Laden und Speichern von Bitmap-Files unter Windows nicht, ohne zusätzlich zum r-/w-Flag noch ein 'b' für "binary" zu setzen.

Ergo könnte man in der Zeile 843 sowie in Zeile 1571 der bitmap.c die Flags erweitern:

```
843   FILE* file = fopen(filePath, "rb");
/* ... */
1571  FILE* file = fopen(filePath, "wb+");
```

Viele Grüße

~braeuert

**Comment by JayTee42** [comment]
Ja, 'b' ist hier generell eine gute Idee. Erledigt in 296afed2066139a4c9816ef00ec32ff078dd65aa, vielen Dank :)
